;;
;; PDDL file for the AIPS2000 Planning Competition
;; based on the data generated by the airport simulator Astras.
;;

;; Author: Andercou Alexandru
;;
;;


(define (domain movie_night)
(:requirements :adl)

(:types food soda people time location movie ticket)  

(:predicates
        
        
              (not-to-mall-p ?p)
              (got-to-mall ?t1  -  time ?p  -  people)
              (got-to-mall-p ?p  -  people)
              (food-bought ?p  -  food ?t  -  time ?p  -  people)
              (food-bought-p ?p  -  people)
              (food-bought-p-at ?t1  -  time ?p  -  people)
              
              (ticket-bought ?tk  -  ticket ?t1  -  time ?p  -  people ?m  -  movie)
              (ticket-bought-p ?p  -  people ?m  -  movie)
              (ticket-bought-p-at ?t1  -  time ?p   -  people)
              
              
              (ticket-used ?tk  -  ticket)
              (soda-bought ?s  -  soda ?t1  -  time ?p  -  people)
              (soda-bought-p ?p   -  people)
              (soda-bought-p-at ?t1  -  time ?p   -  people)
              
              (friend ?p  -  people)
              (friend-arrives ?p  -  people ?t1  -  time)
              (all-friends-arrived)
              (all-friends-bought)
              
              (start-movie  ?m  -  movie ?t2  -  time)
              (movie-starts-at ?m  -  movie ?t1  -  time)
              (movie-started ?m  -  movie)
              (movie-ends-at ?m  -  movie ?t1  -  time)
              (movie-ended ?m  -  movie)
              
              (seen-movie ?m  -  movie ?p  -  people )
              (got-back-home ?p  -  people)
              (back-home ?t1  -  time ?p  -  people)

              
              (got-to-shop ?t1  -  time ?p  -  people)
              (got-to-ticket-boot ?t1  -  time ?p  -  people)
              (got-to-movie)
              (left_shop ?p  -  people )
              (left_shop-at ?t1  -  time ?p  -  people)
              (now ?t1  -  time ) 
              (inside-shop ?p  -  people)
              (inside-tb ?p  -  people)
              (myself ?p  -  people)
              
              
              
              
              
             (later-than ?t1   -  time ?t2   -  time)
             (later-by5min ?t1  -  time ?t2  -  time)
             (later-by30min ?t1  -  time ?t2  -  time)
             (later-by15min ?t1  -  time ?t2  -  time)
             (later-by45min ?t1  -  time ?t2  -  time)
                
              
              
)

(:action buy-soda
:parameters
     (?t1   -  time  ?s  -  soda ?t2  -  time  ?t3  -  time ?p  -  people ?m  -  movie)
 :precondition
     (and        
              (got-to-shop ?t2 ?p) 
              (inside-shop ?p)
              (later-than ?t1 ?t2)
              (movie-starts-at ?m ?t3)
              (later-than ?t3 ?t1)
     
     
     
                  )
 :effect
     (and
         (soda-bought ?s ?t1 ?p)
         (soda-bought-p ?p)
         (soda-bought-p-at ?t1 ?p)
               )
)

(:action buy-food
:parameters
    (?t1   -  time ?f  -  food ?t2  -  time  ?t3  -  time ?p  -  people ?m  -  movie)
:precondition
     (and     (got-to-shop ?t2 ?p) 
              (inside-shop ?p)
              (later-than ?t1 ?t2)
              (movie-starts-at ?m ?t3)
              (later-than ?t3 ?t1)
             
       )
 :effect
     (and
         (food-bought ?f ?t1 ?p)
         (food-bought-p ?p)
         (food-bought-p-at ?t1 ?p)
           )
 )
               




(:action buy-ticket
:parameters
     (?t1  -  time  ?t2  -  time ?t3  -  time ?tk  -  ticket ?p  -  people ?m  -  movie)
 :precondition
     (and     (not (inside-shop ?p))
              (inside-tb ?p)
              (got-to-ticket-boot ?t2 ?p)
              (later-than ?t1 ?t2)
              (movie-starts-at ?m ?t3)
              (later-than ?t3 ?t1)
              (not (ticket-used ?tk))
               )
 :effect
     (and   (ticket-bought ?tk  ?t1  ?p ?m)
            (ticket-bought-p  ?p ?m)
            (ticket-bought-p-at ?t1 ?p)
            (ticket-used ?tk)
               )
)
               




(:action me-go-to-mall
:parameters
     (?t1  -  time   ?t3  -  time ?p  -  people)
 :precondition
     (and     
              (myself ?p)
              (not-to-mall-p ?p)
              (later-by15min ?t3 ?t1)
              (now ?t1)
          
               )
 :effect
     (and   (got-to-mall ?t3 ?p)
           (got-to-mall-p ?p)
          
           
      ( not (not-to-mall-p ?p))
      (not (now ?t1))
      (now ?t3)
)
)

(:action friend-go-to-mall
:parameters
     (?t1  -  time  ?p  -  people)
 :precondition
     (and     
              (friend  ?p)
              (friend-arrives ?p ?t1 )
           
              
              
               )
 :effect
     (and   (got-to-mall ?t1 ?p)
            (got-to-mall-p ?p)
            
          
)
)


(:action go-to-shop
:parameters (?t1  -  time  ?t2   -  time  ?t3  -  time ?p  -  people)
:precondition (and (got-to-mall ?t2 ?p) 
                   (later-than ?t1 ?t2)
                  

)
:effect (and (got-to-shop ?t1 ?p) (inside-shop ?p)
            )

)




(:action leave_shop
:parameters (?t1  -  time  ?t2   -  time  ?t3  -  time ?p  -  people)
:precondition (and (got-to-shop ?t1 ?p) 
                   (later-than ?t2 ?t1)
                   (inside-shop ?p)
)
:effect (and  (left_shop ?p)
              (left_shop-at ?t2 ?p)
              (not (inside-shop ?p))
              
              
              )
)

(:action go-to-ticket-boot

:parameters (?t1  -  time  ?t2   -  time ?t3  -  time ?p  -  people ?m  -  movie)
:precondition (and (got-to-mall ?t1 ?p) (not (inside-shop  ?p))  (later-than ?t2  ?t1)
                 (movie-starts-at ?m ?t3)
                 (later-than ?t3 ?t2)
 )
:effect (and  (got-to-ticket-boot ?t2  ?p )   (inside-tb ?p)) 



)

(:action leave_ticket_boot
:parameters (?t1  -  time  ?t2   -  time  ?t3  -  time ?p  -  people)
:precondition (and (got-to-ticket-boot ?t1 ?p) 
                   (later-than ?t2 ?t1)
)
:effect (and  
              (not (inside-tb ?p))
        )
)




(:action go-to-movie-together-at-first
:parameters (?t1  -  time   ?m  -  movie   ?t2   -  time ?t3  -  time )
:precondition (and 
              (now ?t3)
              (movie-starts-at ?m ?t2)
              (later-than ?t2 ?t1) 
              (later-than ?t1 ?t3)
               ( forall (?p2  -  people) 
              
                 
                  (exists (?t4  -  time ?t5  -  time ?t7  -  time) 
                  (and 
                  (ticket-bought-p-at ?t4  ?p2 )
                  (food-bought-p-at ?t5 ?p2)
                  (soda-bought-p-at ?t7 ?p2)
                  (later-than ?t1 ?t4)
                  (later-than ?t1 ?t5)
                  (later-than ?t1 ?t7)
                  )
                 )
               )
              
              )
:effect (and ( forall (?p3  -  people)  (seen-movie ?m ?p3) ) (not ( now ?t3) ) (now ?t1))



)





(:action movie_starts
:parameters (?t1  -  time  ?m  -  movie)
:precondition (and  (movie-starts-at ?m ?t1)  (now ?t1))
:effect (and (movie-started ?m) )



)

(:action movie_ends
:parameters (?t1  -  time  ?m   - movie)
:precondition (and (movie-started ?m) (movie-ends-at ?m ?t1)  (now ?t1))
:effect (and (movie-ended ?m)  )



)




(:action go_home

:parameters ( ?p  - people ?m  - movie)
:precondition (and (seen-movie ?m ?p)  (movie-ended ?m ) )


:effect (and  (got-back-home ?p))


)








(:action time_passes 
  :parameters  (?t1  -  time  ?t2  -  time)
  :precondition  (and (now ?t1) 
                   (later-than ?t2 ?t1)
                 )
 :effect
 (and
 (not (now ?t1))
 (now ?t2) 
 )
    
    
    

)

)


