;;
;; PDDL file for the AIPS2000 Planning Competition
;; based on the data generated by the airport simulator Astras.
;;

;; Author: Sebastian Trueg thisshouldbethecurrentdateandtime :(
;; Created with SegmentSplitterAirportExporter 0.1 by Sebastian Trueg <trueg@informatik.uni-freiburg.de>
;;



(define (problem PROBLEM_X)

(:domain kitchen)

(:objects

     
     egg1
     egg2
     egg3 
     egg4 - egg
     
     redtomato - tomato
     yellowtomato - tomato
     onion1 - onion 
     onion2 - onion
     onion3 - onion
     
    b - bacon 
    k10 - knife 
    f1 - fork 
    s - salad 
    ov - cooker 
    b1 - boal 
    b2 - boal
     
     ovile_oil - oil
     sunflower_oil - oil
     
     
     
     
)

(:init

(knife-down k10)
(cooker-stoped ov)
)

(:goal
      (meal-made)
)
)
