;;
;; PDDL file for the AIPS2000 Planning Competition
;; based on the data generated by the airport simulator Astras.
;;

;; Author:Andercou Alexandru
;; 
;;


(define (domain city_travel)
(:requirements :adl :strips :typing :action-costs )

(:types moment location course transport meal)    

(:predicates

                (student-at ?l1  - location ?t1  - moment)
                (event-at  ?c1  - course ?l2  - location ?t1  - moment ?t2 - moment)
                (event-attended ?c1 - course)
                (bus-travel-at ?bus ?fr - location ?to  - locaton ?frt  - moment ?tot  - moment)
                (bus-trace ?bus ?fr - location  ?to - location)
                (later-than ?t1  - moment ?t2  - moment)
                (later-by30min ?t1 - moment ?t2 - moment)
                (later-by1h ?t1 - moment ?t2 - moment)
                (later-by2h ?t1 - moment ?t2 - moment)
                (later-by15min ?t1 - moment ?t2 - moment)
                (later-by45min ?t1 - moment ?t2 - moment)
                (not-same-place ?l1 - location ?l2 - location)
                (taxi-at ?l1)
                (bus ?b)
                (taxi ?t)
                (leg ?l)
                (home ?l1 - location)
                (shower-made)
                (ate ?m - meal)
   )
   (:functions
     (pay_for_transport ?s)
     (time_spend_traveling)
     (total-cost))
   

(:action travel_by_taxi_15_min
 :parameters
     (?l1  - location ?l2 - location ?t1  - moment ?t2  - moment ?tx)
 :precondition
     (and       (taxi ?tx)
                (taxi-at ?l1)
                (student-at ?l1 ?t1)
                (later-by15min ?t2 ?t1)
                (not-same-place ?l1 ?l2)
                )
 :effect
     (and
           (not (student-at ?l1 ?t1) )  
           (student-at ?l2 ?t2)
           (increase ( total-cost) (pay_for_transport ?tx) )
           (increase ( total-cost)  2)
               )
               )
               
               
(:action travel_by_bus_30_min
 :parameters
     (?l1  - location ?l2 - location ?t1  - moment ?t2  - moment ?b)
 :precondition
     (and       (bus ?b)
               
                (student-at ?l1 ?t1)
                (later-by30min ?t2 ?t1)
                (not-same-place ?l1 ?l2)
                (bus-trace ?b ?l1 ?l2)
                )
 :effect
     (and
           (not (student-at ?l1 ?t1) )  
           (student-at ?l2 ?t2)
           (increase ( total-cost) (pay_for_transport ?b) )
           (increase ( total-cost) 5 )
               )
               )               
 (:action travel_by_bus_45_min
 :parameters
     (?l1  - location ?l2 - location ?t1  - moment ?t2  - moment ?b)
 :precondition
     (and       (bus ?b)
               
                (student-at ?l1 ?t1)
                (later-by45min ?t2 ?t1)
                (not-same-place ?l1 ?l2)
                (bus-trace ?b ?l1 ?l2)
                )
 :effect
     (and
           (not (student-at ?l1 ?t1) )  
           (student-at ?l2 ?t2)
           (increase ( total-cost) (pay_for_transport ?b) )
           (increase ( total-cost) 5 )
               )
               )
               
                           
(:action travel_by_walk_2h
 :parameters
     (?l1  - location ?l2 - location ?t1  - moment ?t2  - moment ?legs)
 :precondition
     (and       (leg ?legs)
                (student-at ?l1 ?t1)
                (later-by2h ?t2 ?t1)
                (not-same-place ?l1 ?l2)
                )
 :effect
     (and
           (not (student-at ?l1 ?t1) )  
           (student-at ?l2 ?t2)
           (increase (  total-cost ) (pay_for_transport ?legs) )
           (increase ( total-cost) 20 )
               )
               ) 
               
  (:action atends_event
 :parameters
     (?l1  - location  ?t1  - moment  ?t2  - moment ?e1  - course)
 :precondition
     (and
                (student-at ?l1 ?t1)
                (event-at  ?e1  ?l1 ?t1 ?t2)
                )
 :effect
 (and 
    (event-attended ?e1)
    (not (student-at ?l1 ?t1) ) 
    (student-at ?l1 ?t2)
    )
       )                      
               
               
   
               
      (:action call_taxi
 :parameters
     (?l1  - location  ?t1  - moment ?t2  - moment ?l2 - location)
 :precondition
     (and 
                (taxi-at ?l1)
                (student-at ?l1 ?t1)
                (later-by15min ?t2 ?t1)
                )
 :effect
    (and (not (student-at ?l1 ?t1))
         (not (taxi-at ?l1))
      (student-at ?l1 ?t2)
     
      (taxi-at ?l2))
    )
                               
           (:action spend_tree_time
 :parameters
     (?l1  - location  ?t1  - moment ?t2  - moment)
 :precondition
   (and (student-at ?l1 ?t1)
       (later-than ?t2 ?t1)
 )
 :effect
    (and (not (student-at ?l1 ?t1))
      (student-at ?l1 ?t2)
    )
           )              
        (:action do_shower
 :parameters
     ( ?t1  - moment  ?t2  - moment ?l1 - location)
 :precondition
     (and       (home ?l1)
                (student-at ?l1 ?t1)
                (later-by30min ?t2 ?t1)
                )
 :effect
 (and 
    (shower-made)
    (not  (student-at ?l1  ?t1))
    (student-at campus_zorilor ?t2)
    )
       )                      
           (:action eat_out
         :parameters
         ( ?t1  - moment  ?t2  - moment ?l1 - location ?m - meal)
 :precondition
     (and       (not (home ?l1))
                (student-at ?l1 ?t1)
                (later-by30min ?t2 ?t1)
               
                )
 :effect
 (and 
    (ate ?m)
    (not  (student-at  ?l1 ?t1))
    (student-at ?l1 ?t2)
    (increase (  total-cost ) 30 )
    )
       )                      
          (:action eat_inside
         :parameters
         ( ?t1  - moment  ?t2  - moment ?l1 - location ?m - meal)
 :precondition
     (and       (home ?l1)
                (student-at ?l1 ?t1)
                (later-by30min ?t2 ?t1)
                )
 :effect
 (and 
    (ate ?m)
    (not  (student-at ?l1 ?t1))
    (student-at ?l1  ?t2)
    (increase (  total-cost ) 10 )
    )
       )         
                 
               

)
